### ISSUE TITLE
What should this thing be?

### ISSUE THREAD

**Issue by parkr** [jekyll/atom-jekyll#1]
Atom is a pretty freakin' sweet editor which is also highly extensible. But hey, wait, Atom is built on web technologies? We've built something that makes websites! This is surely a match made in heaven! So what would a Jekyll plugin for Atom look like? Some ideas:

- [ ] Keybinding to run `jekyll serve --watch` in the background and open a split pane view of the current page, refreshed every time the user saves the source doc ( @benbalter's idea) 
- [ ] Liquid/YAML front-matter syntax highlighting (maybe make a separate `atom-liquid`?)
- [ ] Tab completion for Liquid tags & Jekyll variables (e.g. `site.*` or `include`)
- [ ] Jump to include file referenced on current line. ( @geekles's idea )
- [ ] Promoting of a draft to a post (from @qrohlf)
- [ ] Your :heart:'s greatest desires

I haven't really looked into the limitations of Atom's plugin system yet, but it doesn't seem like there are any.

/cc @jglovier

**Comment by gkemmey** [comment]
This thread looks inactive, but it's a top result searching google for "atom jekyll syntax highlighting". 

If you're like me and you'd like code highlighting in markdown files using Jekyll code blocks like `{% highlight ruby %}`, I've created this: https://atom.io/packages/jekyll-syntax-highlighting.

**Comment by goldhand** [comment]
Would be nice if @gkemmey's package was included in this one or if it was noted in the readme that this wouldn't add syntax highlighting (maybe with a link to @gkemmey's repo), I just assumed syntax highlighting would be one of the features and had to do some digging. https://atom.io/packages/jekyll-syntax-highlighting works well.

**Comment by parkr** [comment]
> if it was noted in the readme that this wouldn't add syntax highlighting (maybe with a link to @gkemmey's repo)

@goldhand Want to submit a PR for this?

**Comment by goldhand** [comment]
@parkr I thought I was on https://github.com/Arcath/jekyll-atom, is that where I should send pr to? I'm confused what this repo is for now sorry 😆

**Comment by parkr** [comment]
@goldhand Oh haha! If you think it'd be useful, you could submit a PR to this repository which points to jekyll-syntax-highlighting 😄
